Check for dbus/avahi

diff --git a/install/hassio_install b/install/hassio_install
--- a/install/hassio_install
+++ b/install/hassio_install
@@ -17,6 +17,8 @@ command -v docker > /dev/null 2>&1 || { echo "[ERROR] Please install docker firs
 command -v jq > /dev/null 2>&1 || { echo "[ERROR] Please install jq first"; exit 1; }
 command -v socat > /dev/null 2>&1 || { echo "[ERROR] Please install socat first"; exit 1; }
 command -v curl > /dev/null 2>&1 || { echo "[ERROR] Please install curl first"; exit 1; }
+command -v avahi-daemon > /dev/null 2>&1 || { echo "[ERROR] Please install avahi first"; exit 1; }
+command -v dbus-daemon > /dev/null 2>&1 || { echo "[ERROR] Please install dbus first"; exit 1; }
 
 # Check system options
 if [ -x $(command -v systemctl) ]; then
