Next gen installer (#74)
* Update hassio-hc.service

* Rename hassio-hc.service to hassio-apparmor.service

* Update hassio-supervisor.service

* Delete update-manual

* Delete README.md

* Delete 0.3

* Delete 0.2

* Delete 0.1

* Update and rename hassio-start to hassio-supervisor

* Create hassio-apparmor

* Update hassio_install

* Update hassio-supervisor

* Update hassio_install

* Update README.md

* Create apparmor-profile

* Rename install/service/hassio-apparmor to install/files/hassio-apparmor

* Rename install/service/hassio-supervisor to install/files/hassio-supervisor

* Rename install/systemd/hassio-apparmor.service to install/files/hassio-apparmor.service

* Rename install/systemd/hassio-supervisor.service to install/files/hassio-supervisor.service

* Update hassio_install

* Update hassio-supervisor

diff --git a/install/hassio_install b/install/hassio_install
--- a/install/hassio_install
+++ b/install/hassio_install
@@ -3,30 +3,29 @@ set -e
 
 ARCH=$(uname -m)
 DOCKER_REPO=homeassistant
-URL_VERSION="https://raw.githubusercontent.com/home-assistant/hassio/master/version.json"
-URL_START_HASSIO="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/service/hassio-start"
-URL_GENERIC_HC="https://raw.githubusercontent.com/home-assistant/hassio-build/master/generic-hc"
-URL_SERVICE_HASSIO="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/systemd/hassio-supervisor.service"
-URL_SERVICE_HOSTCONTROL="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/systemd/hassio-hc.service"
-
-BIN_DIR=/usr/bin
 DATA_SHARE=/usr/share/hassio
+URL_VERSION="https://raw.githubusercontent.com/home-assistant/hassio/master/version.json"
+URL_BIN_HASSIO="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/files/hassio-supervisor"
+URL_BIN_APPARMOR="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/files/hassio-apparmor"
+URL_SERVICE_HASSIO="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/files/hassio-supervisor.service"
+URL_SERVICE_APPARMOR="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/files/hassio-apparmor.service"
+URL_APPARMOR_PROFILE="https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/files/apparmor-profile"
 
 # Check env
-command -v docker > /dev/null 2>&1 || { echo "[ERROR] Please install docker first"; exit 1; }
-command -v jq > /dev/null 2>&1 || { echo "[ERROR] Please install jq first"; exit 1; }
-command -v socat > /dev/null 2>&1 || { echo "[ERROR] Please install socat first"; exit 1; }
-command -v curl > /dev/null 2>&1 || { echo "[ERROR] Please install curl first"; exit 1; }
-command -v avahi-daemon > /dev/null 2>&1 || { echo "[ERROR] Please install avahi first"; exit 1; }
-command -v dbus-daemon > /dev/null 2>&1 || { echo "[ERROR] Please install dbus first"; exit 1; }
+command -v systemctl > /dev/null 2>&1 || { echo "[Error] Only systemd is supported!"; exit 1; }
+command -v docker > /dev/null 2>&1 || { echo "[Error] Please install docker first"; exit 1; }
+command -v jq > /dev/null 2>&1 || { echo "[Error] Please install jq first"; exit 1; }
+command -v curl > /dev/null 2>&1 || { echo "[Error] Please install curl first"; exit 1; }
+command -v avahi-daemon > /dev/null 2>&1 || { echo "[Error] Please install avahi first"; exit 1; }
+command -v dbus-daemon > /dev/null 2>&1 || { echo "[Error] Please install dbus first"; exit 1; }
+command -v apparmor_parser > /dev/null 2>&1 || echo "[Warning] No AppArmor support on Host."
+command -v nmcli > /dev/null 2>&1 || echo "[Warning] No NetworkManager support on Host."
 
-# Check system options
-if [ -x $(command -v systemctl) ]; then
-    INIT_SYSTEM=systemd
+# AppArmor Support
+if command -v apparmor_parser > /dev/null 2>&1; then
+    APPARMOR=no
 else
-    INIT_SYSTEM=sysvinit
-    echo "[ERROR] Only systemd is supprted at the moment"
-    exit 1
+    APPARMOR=yes
 fi
 
 # Parse command line parameters
@@ -35,21 +34,16 @@ while [[ $# > 0 ]]; do
 
     case $arg in
         -m|--machine)
-            if [ -z "$2" ]; then
-                echo "[ERROR] \"$1\" argument needs a value"
-            fi
             MACHINE=$2
             shift
             ;;
         -d|--data-share)
-            if [ -z "$2" ]; then
-                echo "[ERROR] \"$1\" argument needs a value"
-            fi
             DATA_SHARE=$2
             shift
             ;;
         *)
-            echo "[ERROR] Unrecognized option $1"
+            echo "[Error] Unrecognized option $1"
+            exit 1
             ;;
     esac
     shift
@@ -84,10 +78,16 @@ case $ARCH in
         HASSIO_DOCKER="$DOCKER_REPO/aarch64-hassio-supervisor"
     ;;
     *)
-        echo "[ERROR] $ARCH unknown!"
+        echo "[Error] $ARCH unknown!"
         exit 1
     ;;
 esac
+
+if [ -z "${HOMEASSISTANT_DOCKER}" ]; then
+    echo "[Error] Found no Home Assistant docker images for this host!"
+fi
+
+### Main
 
 # Init folders
 if [ ! -d "$DATA_SHARE" ]; then
@@ -96,45 +96,48 @@ fi
 
 # Read infos from web
 HASSIO_VERSION=$(curl -s $URL_VERSION | jq -e -r '.hassio')
-GENERIC_HC_VERSION=$(curl -s $URL_VERSION | jq -e -r '.generic')
 
 ##
-# Install supervisor
-echo "[INFO] Install supervisor docker"
+# Write config
+cat > /etc/hassio.json <<- EOF
+{
+    "supervisor": "${HASSIO_DOCKER}",
+    "homeassistant": "${HOMEASSISTANT_DOCKER}",
+    "data": "${DATA_SHARE}"
+}
+EOF
+
+##
+# Pull supervisor image
+echo "[Info] Install supervisor docker"
 docker pull "$HASSIO_DOCKER:$HASSIO_VERSION" > /dev/null
 docker tag "$HASSIO_DOCKER:$HASSIO_VERSION" "$HASSIO_DOCKER:latest" > /dev/null
 
 ##
-# Install generic hostcontrol
-echo "[INFO] Install generic HostControl"
-curl -sL "$URL_GENERIC_HC/$GENERIC_HC_VERSION" > "$BIN_DIR/hassio-hc"
+# Install Hass.io Supervisor
+echo "[Info] Install supervisor startup scripts"
+curl -sL ${URL_START_HASSIO} > /usr/bin/hassio-supervisor
+curl -sL ${URL_SERVICE_HASSIO} > /etc/systemd/system/hassio-supervisor.service
 
-chmod a+x "$BIN_DIR/hassio-hc"
+chmod a+x /usr/bin/hassio-supervisor
+systemctl enable hassio-supervisor.service
 
-##
-# Install start-hassio
-echo "[INFO] Install startup scripts"
-curl -sL "$URL_START_HASSIO" > "$BIN_DIR/hassio-start"
+#
+# Install Hass.io AppArmor
+if [ "$APPARMOR" == "yes" ]; then
+    echo "[Info] Install AppArmor scripts"
+    mkdir -p ${DATA_SHARE}/apparmor
+    curl -sL ${URL_BIN_APPARMOR} > /usr/bin/hassio-apparmor
+    curl -sL ${URL_SERVICE_APPARMOR} > /etc/systemd/system/hassio-apparmor.service
+    curl -sL ${URL_APPARMOR_PROFILE} > ${DATA_SHARE}/apparmor/hassio-supervisor
 
-sed -i "s|%%SUPERVISOR_IMAGE%%|$HASSIO_DOCKER|g" "$BIN_DIR/hassio-start"
-sed -i "s|%%HOMEASSISTANT_IMAGE%%|$HOMEASSISTANT_DOCKER|g" "$BIN_DIR/hassio-start"
-sed -i "s|%%DATA_SHARE%%|$DATA_SHARE|g" "$BIN_DIR/hassio-start"
+    chmod a+x /usr/bin/hassio-apparmor
+    systemctl enable hassio-apparmor.service
 
-chmod a+x "$BIN_DIR/hassio-start"
+    systemctl start hassio-apparmor.service
+fi
 
 ##
 # Init system
-if [ "$INIT_SYSTEM" == "systemd" ]; then
-    echo "[INFO] Init systemd"
-    curl -sL "$URL_SERVICE_HASSIO" > "/etc/systemd/system/hassio-supervisor.service"
-    curl -sL "$URL_SERVICE_HOSTCONTROL" > "/etc/systemd/system/hassio-hc.service"
-
-    sed -i "s|%%BIN_DIR%%|$BIN_DIR|g" "/etc/systemd/system/hassio-hc.service"
-    sed -i "s|%%BIN_DIR%%|$BIN_DIR|g" "/etc/systemd/system/hassio-supervisor.service"
-
-    systemctl enable hassio-supervisor.service
-
-    echo "[INFO] Start services"
-    systemctl start hassio-hc.service
-    systemctl start hassio-supervisor.service
-fi
+echo "[Info] Run Hass.io"
+systemctl start hassio-supervisor.service
